#ifndef APP_H
#define APP_H

/*
 * app.h  –  Central header for CatiaMenuWin32
 * Mirrors the single-header style used in MineSweeperWin32.
 */

#define WIN32_LEAN_AND_MEAN
#define UNICODE
#define _UNICODE
#include <windows.h>
#include <commctrl.h>
#include <wininet.h>
#include <shellapi.h>
#include <shlwapi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "resource_ids.h"
#include "version.h"          /* generated by CMake from version.h.in */

/* ─── Application strings ──────────────────────────────────────────── */
#define APP_CLASS       L"CatiaMenuWin32Class"
#define APP_TITLE       L"CATIA Macro Menu"
#define GITHUB_OWNER    L"KaiUR"
#define GITHUB_REPO     L"Pycatia_Scripts"
#define GITHUB_BRANCH   L"main"
#define GITHUB_API_HOST L"api.github.com"
#define GITHUB_RAW_HOST L"raw.githubusercontent.com"
#define SETTINGS_FILE   L"Data\\settings.ini"

/* ─── Window layout constants ──────────────────────────────────────── */
#define WIN_MIN_W       560
#define WIN_MIN_H       420
#define TOOLBAR_H       38
#define STATUS_H        22
#define BTN_H           36
#define BTN_GAP         6
#define BTN_MARGIN_X    12
#define BTN_MARGIN_Y    10
#define SCROLL_SPEED    40

/* ─── Limits ───────────────────────────────────────────────────────── */
#define MAX_FOLDERS     16
#define MAX_SCRIPTS     64
#define MAX_NAME        128
#define MAX_PATH_APP    520
#define HTTP_BUF        (512 * 1024)   /* 512 KB read buffer */

/* ─── Custom window messages ───────────────────────────────────────── */
#define WM_FETCH_DONE      (WM_USER + 1)  /* wParam = 0 ok / 1 error */
#define WM_STATUS_SET      (WM_USER + 2)  /* lParam = WCHAR* (heap, caller frees) */

/* ─── Colour palette  (dark industrial theme) ─────────────────────── */
#define COL_BG          RGB(28,  28,  35)
#define COL_PANEL       RGB(36,  36,  46)
#define COL_TOOLBAR     RGB(20,  20,  28)
#define COL_BTN_NORM    RGB(48,  50,  70)
#define COL_BTN_HOT     RGB(65,  68,  95)
#define COL_BTN_PRESS   RGB(30,  32,  50)
#define COL_ACCENT      RGB(82, 155, 245)   /* bright blue */
#define COL_ACCENT_DIM  RGB(50,  95, 160)
#define COL_SUCCESS     RGB(80, 200, 120)
#define COL_WARN        RGB(240, 190,  60)
#define COL_ERROR       RGB(230,  80,  80)
#define COL_TEXT        RGB(210, 215, 240)
#define COL_SUBTEXT     RGB(120, 125, 155)
#define COL_DIVIDER     RGB(50,  52,  68)
#define COL_TAB_ACTIVE  RGB(82, 155, 245)
#define COL_TAB_NORM    RGB(40,  42,  58)

/* ─── Structures ───────────────────────────────────────────────────── */

typedef struct {
    WCHAR name[MAX_NAME];        /* display name (snake_case stripped, formatted) */
    WCHAR gh_path[MAX_PATH_APP]; /* repo-relative path, e.g. Part_Document_Scripts/foo.py */
    WCHAR description[256];      /* first docstring line from README or empty */
} Script;

typedef struct {
    WCHAR   name[MAX_NAME];          /* folder name as it appears in the repo */
    WCHAR   display[MAX_NAME];       /* formatted for the tab label */
    Script  scripts[MAX_SCRIPTS];
    int     count;
    bool    loaded;
} Folder;

typedef struct {
    WCHAR python_exe[MAX_PATH_APP];  /* full path to python.exe */
    WCHAR cache_dir[MAX_PATH_APP];   /* local dir where scripts are cached */
    WCHAR github_token[256];         /* optional PAT */
    bool  download_before_run;       /* fetch latest before executing */
    bool  show_console;              /* CREATE_NO_WINDOW vs normal */
} Settings;

typedef struct {
    /* Window handles */
    HWND  hwnd;
    HWND  hwnd_tab;
    HWND  hwnd_status;
    HWND  hwnd_scroll;      /* scrollable content area */

    /* Data */
    Folder   folders[MAX_FOLDERS];
    int      folder_count;
    int      active_tab;
    Settings cfg;

    /* GDI resources */
    HFONT    font_ui;
    HFONT    font_bold;
    HFONT    font_small;
    HBRUSH   br_bg;
    HBRUSH   br_panel;
    HBRUSH   br_toolbar;
    HBRUSH   br_btn;
    HBRUSH   br_btn_hot;
    HBRUSH   br_accent;

    /* State */
    bool     fetching;
    int      hot_btn;        /* IDC_SCRIPT_BTN_BASE + idx, or -1 */
    WCHAR    last_run[MAX_PATH_APP];
    int      scroll_y;
    int      scroll_max;
} AppState;

/* Global singleton – defined in main.c */
extern AppState g_app;

/* ─── Prototypes ────────────────────────────────────────────────────── */

/* main.c */
int WINAPI    wWinMain(HINSTANCE, HINSTANCE, LPWSTR, int);
LRESULT CALLBACK MainWndProc(HWND, UINT, WPARAM, LPARAM);
void      App_InitResources(void);
void      App_FreeResources(void);

/* window.c */
void      Window_Create(HINSTANCE hInst);
void      Window_OnSize(int w, int h);
void      Window_OnScroll(HWND hwnd, WPARAM wp);
void      Window_ShowAbout(HWND parent);

/* tabs.c */
void      Tabs_Build(void);
void      Tabs_Switch(int idx);
void      Tabs_RebuildButtons(void);
void      Tabs_DestroyButtons(void);
LRESULT CALLBACK ScrollPanelProc(HWND, UINT, WPARAM, LPARAM);

/* github.c */
DWORD WINAPI  GitHub_FetchThread(LPVOID);
bool          GitHub_HttpGetA(const WCHAR *host, const WCHAR *path,
                               const WCHAR *token,
                               char *buf, DWORD *len);
void          GitHub_ParseRoot(const char *json);
void          GitHub_ParseFolder(const char *json, int fi);

/* runner.c */
bool          Runner_Run(int folder_idx, int script_idx);
DWORD WINAPI  Runner_Thread(LPVOID arg);
bool          Runner_DownloadScript(const WCHAR *gh_path, const WCHAR *local_path);
bool          Runner_FindPython(WCHAR *out, int max);

/* settings.c */
void          Settings_Load(Settings *s);
void          Settings_Save(const Settings *s);
INT_PTR CALLBACK SettingsDlgProc(HWND, UINT, WPARAM, LPARAM);

/* paint.c */
void          Paint_MainWindow(HWND hwnd, HDC hdc);
void          Paint_Toolbar(HDC hdc, RECT *rc);
void          Paint_ScriptButton(HWND hwnd_btn, HDC hdc, bool hot, bool pressed,
                                 const WCHAR *label, const WCHAR *desc);
LRESULT CALLBACK BtnSubclassProc(HWND, UINT, WPARAM, LPARAM, UINT_PTR, DWORD_PTR);

/* util (inline helpers in app.h) */
static inline void Util_StripExt(WCHAR *s) {
    WCHAR *dot = wcsrchr(s, L'.');
    if (dot) *dot = L'\0';
}

static inline void Util_SnakeToTitle(WCHAR *s) {
    /* Replace underscores with spaces, capitalize after each */
    bool cap = true;
    for (WCHAR *p = s; *p; p++) {
        if (*p == L'_') { *p = L' '; cap = true; }
        else if (cap)   { *p = (WCHAR)towupper(*p); cap = false; }
    }
}

#endif /* APP_H */
