/*
 * paint.c  -  All GDI rendering. Double-buffered throughout.
 * CatiaMenuWin32
 * Author : Kai-Uwe Rathjen
 * AI Assistance: Claude (Anthropic)
 * License: MIT
 */

#include "main.h"

/* Fallback if version.h not yet regenerated by CMake */
#ifndef VERSION_STRING_W
#define VERSION_STRING_W VERSION_STRING_W
#endif
#ifndef IS_LOCAL_BUILD
#define IS_LOCAL_BUILD 1
#endif

/* ================================================================== */
/*  DrawRoundRect  (static)                                            */
/*  Purpose: Draws a filled rounded rectangle with a border using a   */
/*           single GDI RoundRect call.  When fill == border, uses    */
/*           a null pen so the border does not double-draw.            */
/*  In:  hdc    — target device context                                */
/*       x, y   — top-left corner                                      */
/*       w, h   — dimensions in pixels                                  */
/*       r      — corner ellipse radius                                 */
/*       fill   — interior fill colour                                  */
/*       border — outline colour (use same as fill to suppress border) */
/*  Out: (void)                                                         */
/* ================================================================== */
static void DrawRoundRect(HDC hdc, int x, int y, int w, int h, int r,
                           COLORREF fill, COLORREF border)
{
    HBRUSH br  = CreateSolidBrush(fill);
    HPEN   pen = (border == fill) ? (HPEN)GetStockObject(NULL_PEN) /* no border wanted — use stock pen to avoid double-drawing */
                                  : CreatePen(PS_SOLID, 1, border);
    HBRUSH obr = SelectObject(hdc, br);
    HPEN   ope = SelectObject(hdc, pen);
    RoundRect(hdc, x, y, x + w, y + h, r, r);
    SelectObject(hdc, obr); SelectObject(hdc, ope);
    DeleteObject(br);
    if (border != fill) DeleteObject(pen); /* don't delete the stock NULL_PEN — it is not owned by us */
}

/* ================================================================== */
/*  Paint_MainWindow                                                    */
/*  Purpose: Renders the main window background via a double-buffered  */
/*           memory DC.  Draws the toolbar band, a divider line, and  */
/*           the app title/version string.  Shows an update-available  */
/*           badge or a "Syncing…" indicator in the toolbar when active.*/
/*  In:  hwnd      — main window handle (for client rect)              */
/*       hdc_paint — device context from BeginPaint (render target)   */
/*  Out: (void)                                                         */
/* ================================================================== */
void Paint_MainWindow(HWND hwnd, HDC hdc_paint)
{
    RECT rc; GetClientRect(hwnd, &rc);
    int w = rc.right, h = rc.bottom;

    HDC     mem = CreateCompatibleDC(hdc_paint);
    HBITMAP bmp = CreateCompatibleBitmap(hdc_paint, w, h);
    HBITMAP old = SelectObject(mem, bmp);

    HBRUSH bg = CreateSolidBrush(COL_BG());
    FillRect(mem, &rc, bg);
    DeleteObject(bg);

    RECT tb = { 0, 0, w, TOOLBAR_H };
    HBRUSH tb_br = CreateSolidBrush(COL_TOOLBAR());
    FillRect(mem, &tb, tb_br);
    DeleteObject(tb_br);

    HPEN dp = CreatePen(PS_SOLID, 1, COL_DIVIDER());
    HPEN op = SelectObject(mem, dp);
    MoveToEx(mem, 0, TOOLBAR_H - 1, NULL); /* TOOLBAR_H - 1 = one px below toolbar band = divider line */
    LineTo(mem, w, TOOLBAR_H - 1);
    SelectObject(mem, op); DeleteObject(dp);

    SetBkMode(mem, TRANSPARENT);
    HFONT of = SelectObject(mem, g.font_bold);

    /* Build title string with version */
    WCHAR title[128];
    _snwprintf_s(title, 127, _TRUNCATE, L"%s   v%s", APP_TITLE, VERSION_STRING_W);

    if (g.latest_version[0]) { /* update badge pending — split toolbar into two text rows */
        SetTextColor(mem, COL_ACCENT);
        SelectObject(mem, g.font_bold);
        RECT tr = { 440, 0, w - 8, TOOLBAR_H / 2 }; /* 440 = starts right of toolbar buttons; top half of bar */
        DrawText(mem, title, -1, &tr, DT_RIGHT | DT_VCENTER | DT_SINGLELINE);

        WCHAR upd[64];
        _snwprintf_s(upd, 63, _TRUNCATE, L"\u2B06 Update %s available", g.latest_version);
        SelectObject(mem, g.font_small);
        SetTextColor(mem, COL_WARN);
        RECT ur = { 444, TOOLBAR_H / 2, w - 8, TOOLBAR_H - 2 };
        DrawText(mem, upd, -1, &ur, DT_RIGHT | DT_VCENTER | DT_SINGLELINE);
    } else if (g.syncing) { /* no update pending, but sync is in progress */
        SetTextColor(mem, COL_ACCENT);
        RECT tr = { 440, 0, w - 8, TOOLBAR_H / 2 };
        DrawText(mem, title, -1, &tr, DT_RIGHT | DT_VCENTER | DT_SINGLELINE);
        SelectObject(mem, g.font_small);
        SetTextColor(mem, COL_WARN);
        RECT sr = { 444, TOOLBAR_H / 2, w - 8, TOOLBAR_H - 2 };
        DrawText(mem, L"\u25CF Syncing\u2026", -1, &sr,
                 DT_RIGHT | DT_VCENTER | DT_SINGLELINE);
    } else {
        SetTextColor(mem, COL_ACCENT);
        RECT tr = { 440, 0, w - 8, TOOLBAR_H };
        DrawText(mem, title, -1, &tr, DT_RIGHT | DT_VCENTER | DT_SINGLELINE);
    }

    SelectObject(mem, of);
    BitBlt(hdc_paint, 0, 0, w, h, mem, 0, 0, SRCCOPY);
    SelectObject(mem, old); DeleteObject(bmp); DeleteDC(mem);
}

/* ================================================================== */
/*  Paint_ToolbarButton                                                 */
/*  Purpose: Owner-draw handler for toolbar buttons (Menu, Refresh,    */
/*           Settings, Deps, Stop).  Draws a rounded rectangle with    */
/*           pressed/hot/normal/disabled background and text colour.   */
/*           The Stop button uses a red accent when enabled.           */
/*  In:  dis — DRAWITEMSTRUCT provided by WM_DRAWITEM (contains DC,    */
/*             item state, and button label text)                       */
/*  Out: (void)                                                         */
/* ================================================================== */
void Paint_ToolbarButton(DRAWITEMSTRUCT *dis)
{
    HDC  hdc = dis->hDC;
    RECT rc  = dis->rcItem;
    int  w   = rc.right  - rc.left;
    int  h   = rc.bottom - rc.top;

    HDC     mem = CreateCompatibleDC(hdc);
    HBITMAP bmp = CreateCompatibleBitmap(hdc, w, h);
    HBITMAP old = SelectObject(mem, bmp);

    bool pressed  = (dis->itemState & ODS_SELECTED) != 0; /* ODS_SELECTED = button is being clicked */
    bool hot      = (dis->itemState & ODS_HOTLIGHT)  != 0;
    bool focused  = (dis->itemState & ODS_FOCUS)      != 0;
    bool disabled = (dis->itemState & ODS_DISABLED)   != 0;
    bool is_stop  = ((int)dis->CtlID == IDC_BTN_STOP); /* Stop button gets red colour treatment */

#define COL_STOP_ACTIVE  RGB(200, 60, 60)
#define COL_STOP_HOT     RGB(230, 90, 90)

    COLORREF bg  = (pressed && !disabled) ? COL_BTN_PRESS()
                 : (hot && !disabled)      ? COL_BTN_HOT()
                 :                           COL_BTN_NORM();
    COLORREF bdr = disabled          ? COL_DIVIDER()
                 : (hot || focused)  ? (is_stop ? COL_STOP_ACTIVE : COL_ACCENT)
                 :                      COL_DIVIDER();
    COLORREF txt = disabled          ? COL_SUBTEXT()
                 : (hot || pressed)  ? (is_stop ? COL_STOP_HOT : COL_ACCENT)
                 : is_stop           ? COL_STOP_ACTIVE
                 :                     COL_TEXT();

#undef COL_STOP_ACTIVE
#undef COL_STOP_HOT

    DrawRoundRect(mem, 0, 0, w, h, 6, bg, bdr); /* 6 = corner radius */

    /* Button label */
    WCHAR text[64] = {0};
    GetWindowText(dis->hwndItem, text, 63);

    SetBkMode(mem, TRANSPARENT);
    SetTextColor(mem, txt);
    HFONT of = SelectObject(mem, g.font_ui);
    RECT tr = { 0, 0, w, h };
    DrawText(mem, text, -1, &tr,
             DT_CENTER | DT_VCENTER | DT_SINGLELINE);

    SelectObject(mem, of);
    BitBlt(hdc, 0, 0, w, h, mem, 0, 0, SRCCOPY);
    SelectObject(mem, old); DeleteObject(bmp); DeleteDC(mem);
}

/* ================================================================== */
/*  Paint_ScriptButton                                                  */
/*  Purpose: Renders a single script button with a main click zone and */
/*           an "i" info zone on the right.  Hot/pressed states change */
/*           the background and accent bar.  Shows script name in bold */
/*           and purpose as a smaller subtitle when available.         */
/*  In:  hwnd_btn  — button window handle (for client rect)            */
/*       hdc       — DC to render into (may be from DRAWITEMSTRUCT)    */
/*       hot       — true when the mouse is over the main click zone   */
/*       pressed   — true when left button is held                     */
/*       info_hot  — true when the mouse is over the "i" zone          */
/*       repeat    — true when this script is in repeat mode (amber)   */
/*       running   — true when this script is currently executing      */
/*       s         — pointer to the Script to display (may be NULL)    */
/*  Out: (void)                                                         */
/* ================================================================== */
void Paint_ScriptButton(HWND hwnd_btn, HDC hdc,
                         bool hot, bool pressed, bool info_hot, bool repeat,
                         bool running, const Script *s)
{
    RECT rc; GetClientRect(hwnd_btn, &rc);
    int w = rc.right, h = rc.bottom;
    int main_w = w - INFO_BTN_W; /* rightmost INFO_BTN_W px is the "i" info zone; rest is the run area */

    HDC     mem = CreateCompatibleDC(hdc);
    HBITMAP bmp = CreateCompatibleBitmap(hdc, w, h);
    HBITMAP old = SelectObject(mem, bmp);

    /* Idle background: apply source tint when tinting is enabled and state is neither hot nor pressed */
    COLORREF idle_bg = COL_BTN_NORM();
    if (!pressed && !hot && s && g.cfg.tint_script_sources) {
        if      (s->source == SCRIPT_SRC_LOCAL) idle_bg = COL_BTN_LOCAL();
        else if (s->source == SCRIPT_SRC_EXTRA) idle_bg = COL_BTN_EXTRA();
    }
    COLORREF bg  = pressed ? COL_BTN_PRESS() : hot ? COL_BTN_HOT() : idle_bg;
    COLORREF bdr = repeat ? COL_WARN : running ? COL_SUCCESS : hot ? COL_ACCENT : COL_DIVIDER(); /* border priority: repeat > running > hot > idle */
    DrawRoundRect(mem, 0,      0, main_w,     h, 7, bg, bdr);
    DrawRoundRect(mem, main_w, 0, INFO_BTN_W, h, 7,
                  info_hot ? COL_ACCENT_DIM : COL_INFO_ZONE(), bdr);

    SetBkMode(mem, TRANSPARENT);
    SetTextColor(mem, info_hot ? COL_TEXT() : COL_SUBTEXT());
    HFONT of = SelectObject(mem, g.font_bold);
    RECT ir = { main_w, 0, w, h };
    DrawText(mem, L"i", -1, &ir, DT_CENTER | DT_VCENTER | DT_SINGLELINE);

    /* Left accent bar — 4 px wide, 5 px inset top and bottom */
    if (repeat) {
        HBRUSH ab = CreateSolidBrush(COL_WARN);
        RECT   ar = { 0, 5, 4, h - 5 };
        FillRect(mem, &ar, ab);
        DeleteObject(ab);
    } else if (running) {
        HBRUSH ab = CreateSolidBrush(COL_SUCCESS);
        RECT   ar = { 0, 5, 4, h - 5 };
        FillRect(mem, &ar, ab);
        DeleteObject(ab);
    } else if (hot || pressed) {
        HBRUSH ab = CreateSolidBrush(pressed ? COL_ACCENT_DIM : COL_ACCENT);
        RECT   ar = { 0, 5, 4, h - 5 };
        FillRect(mem, &ar, ab);
        DeleteObject(ab);
    }

    SetTextColor(mem, repeat ? COL_WARN : running ? COL_SUCCESS : hot ? COL_ACCENT : COL_SUBTEXT());
    SelectObject(mem, g.font_ui);
    RECT arr = { 8, 0, 28, h }; /* columns 8–28 = small arrow/loop icon area */
    /* Show repeat loop symbol (\u21BB) when in repeat mode, arrow otherwise */
    DrawText(mem, repeat ? L"\u21BB" : L"\u25BA", -1, &arr,
             DT_CENTER | DT_VCENTER | DT_SINGLELINE);

    WCHAR fallback[MAX_NAME] = {0};
    if (!s || !s->name[0])
        GetWindowText(hwnd_btn, fallback, MAX_NAME - 1);

    const WCHAR *label   = (s && s->name[0]) ? s->name : fallback;
    const WCHAR *purpose = (s && s->meta_loaded && s->meta.purpose[0])
                           ? s->meta.purpose : NULL;

    SetTextColor(mem, repeat ? COL_WARN : running ? COL_SUCCESS : hot ? COL_ACCENT : COL_TEXT());
    SelectObject(mem, g.font_bold);
    if (purpose) {
        RECT lr = { 30, 3, main_w - 6, h / 2 + 2 }; /* name in top half; 30 = past the arrow icon */
        DrawText(mem, label, -1, &lr,
                 DT_LEFT | DT_VCENTER | DT_SINGLELINE | DT_END_ELLIPSIS);
        SetTextColor(mem, COL_SUBTEXT());
        SelectObject(mem, g.font_small);
        RECT pr = { 30, h / 2, main_w - 6, h - 4 }; /* purpose in bottom half */
        DrawText(mem, purpose, -1, &pr,
                 DT_LEFT | DT_TOP | DT_SINGLELINE | DT_END_ELLIPSIS);
    } else {
        RECT lr = { 30, 0, main_w - 6, h };
        DrawText(mem, label, -1, &lr,
                 DT_LEFT | DT_VCENTER | DT_SINGLELINE | DT_END_ELLIPSIS);
    }

    SelectObject(mem, of);
    BitBlt(hdc, 0, 0, w, h, mem, 0, 0, SRCCOPY);
    SelectObject(mem, old); DeleteObject(bmp); DeleteDC(mem);
}

/* ================================================================== */
/*  Tip_ComputeHeight  (static)                                        */
/*  Purpose: Calculates the required pixel height for the tooltip popup */
/*           based on the fixed header rows plus the word-wrapped       */
/*           height of the description text (if any).                  */
/*  In:  s — script whose metadata drives the height calculation        */
/*  Out: total pixel height for the tooltip window                      */
/* ================================================================== */
static int Tip_ComputeHeight(const Script *s)
{
    /* Fixed rows: Script + Purpose + Author + Version + Date; 8 = top padding */
    int h = 8 + TIP_HEADER_ROWS * TIP_ROW_H;

    if (s && s->meta.description[0]) {
        h += 6; /* separator + gap */
        /* Use a memory DC with the exact font to get accurate word-wrap height */
        HDC screen = GetDC(NULL);
        HDC mem    = CreateCompatibleDC(screen);
        HFONT of   = SelectObject(mem, g.font_small);
        /* Width must match what Paint_Tooltip draws into; height 0 because DT_CALCRECT fills it in */
        RECT dr = { 0, 0, TIP_W - 14, 0 }; /* TIP_W - 14 = TIP_W minus 8+6 side margins */
        int text_h = DrawText(mem, s->meta.description, -1, &dr,
                              DT_LEFT | DT_TOP | DT_WORDBREAK | DT_CALCRECT);
        SelectObject(mem, of);
        DeleteDC(mem);
        ReleaseDC(NULL, screen);
        h += text_h + 10; /* 10 = separator gap above description */
    }
    h += 10; /* 10 px bottom padding */
    return h;
}

/* ================================================================== */
/*  Paint_Tooltip                                                       */
/*  Purpose: Renders the floating tooltip popup for the script under   */
/*           the "i" button.  Draws a bordered panel with Script,      */
/*           Purpose, Author, Version, Date rows, and a word-wrapped   */
/*           description block below a divider line.                   */
/*  In:  hwnd — the CMW32Tip popup window handle (provides client rect)*/
/*  Out: (void — paints directly to the window via BeginPaint/EndPaint)*/
/* ================================================================== */
void Paint_Tooltip(HWND hwnd)
{
    RECT rc; GetClientRect(hwnd, &rc);
    int w = rc.right, h = rc.bottom;

    PAINTSTRUCT ps;
    HDC hdc = BeginPaint(hwnd, &ps);
    HDC mem = CreateCompatibleDC(hdc);
    HBITMAP bmp = CreateCompatibleBitmap(hdc, w, h);
    HBITMAP old = SelectObject(mem, bmp);

    HBRUSH bg = CreateSolidBrush(COL_TIP_BG());
    FillRect(mem, &rc, bg);
    DeleteObject(bg);

    HPEN bp = CreatePen(PS_SOLID, 1, COL_TIP_BORDER);
    HPEN op = SelectObject(mem, bp);
    HBRUSH nb = SelectObject(mem, GetStockObject(NULL_BRUSH));
    Rectangle(mem, 0, 0, w, h);
    SelectObject(mem, op); SelectObject(mem, nb);
    DeleteObject(bp);

    int fi = g.active_tab;
    int si = g.tip_btn - IDC_SCRIPT_BTN_BASE; /* recover script index from stored button ID */
    if (fi < 0 || fi >= g.folder_count ||
        si < 0 || si >= g.folders[fi].count) goto done; /* invalid index — paint empty panel only */

    {
        Script *s = &g.folders[fi].scripts[si];

        struct { const WCHAR *lbl; const WCHAR *val; } rows[] = {
            { L"Script:",  s->name },
            { L"Purpose:", s->meta.purpose[0]  ? s->meta.purpose  : L"--" },
            { L"Author:",  s->meta.author[0]   ? s->meta.author   : L"--" },
            { L"Version:", s->meta.version[0]  ? s->meta.version  : L"--" },
            { L"Date:",    s->meta.date[0]     ? s->meta.date     : L"--" },
            { NULL, NULL }
        };

        SetBkMode(mem, TRANSPARENT);
        int y = 8;
        for (int i = 0; rows[i].lbl; i++) {
            RECT lr = { 8, y, 76, y + 16 }; /* 76 px = label column right edge */
            RECT vr = { 80, y, w - 6, y + 16 }; /* 80 = value column start; w-6 = right margin */
            SelectObject(mem, g.font_bold);
            SetTextColor(mem, COL_ACCENT);
            DrawText(mem, rows[i].lbl, -1, &lr, DT_LEFT | DT_TOP | DT_SINGLELINE);
            SelectObject(mem, g.font_ui);
            SetTextColor(mem, COL_TEXT());
            DrawText(mem, rows[i].val, -1, &vr,
                     DT_LEFT | DT_TOP | DT_SINGLELINE | DT_END_ELLIPSIS);
            y += TIP_ROW_H;
        }

        if (s->meta.description[0]) {
            HPEN sep = CreatePen(PS_SOLID, 1, COL_DIVIDER());
            HPEN os  = SelectObject(mem, sep);
            MoveToEx(mem, 8, y, NULL); LineTo(mem, w - 8, y);
            SelectObject(mem, os); DeleteObject(sep);
            y += 5;
            /* Full word-wrapped description - no ellipsis, no clipping */
            RECT dr = { 8, y, w - 6, h - 6 };
            SelectObject(mem, g.font_small);
            SetTextColor(mem, COL_SUBTEXT());
            DrawText(mem, s->meta.description, -1, &dr,
                     DT_LEFT | DT_TOP | DT_WORDBREAK);
        }
    }

done:
    BitBlt(hdc, 0, 0, w, h, mem, 0, 0, SRCCOPY);
    SelectObject(mem, old); DeleteObject(bmp); DeleteDC(mem);
    EndPaint(hwnd, &ps);
}

/* ================================================================== */
/*  BtnSubclassProc                                                     */
/*  Purpose: SetWindowSubclass callback installed on every script button*/
/*           (via Tabs_RebuildButtons).  Manages hot-tracking, tooltip  */
/*           show/hide with dynamic sizing, right-click context menu   */
/*           (Details, Run with Args, Favourite, Note, Hide), and left- */
/*           click suppression when the click lands on the "i" zone.   */
/*  In:  hwnd — subclassed button window                               */
/*       msg  — Windows message                                        */
/*       wp   — WPARAM                                                  */
/*       lp   — LPARAM (mouse coords for WM_MOUSEMOVE / WM_LBUTTONUP)  */
/*       uid  — subclass ID = button control ID (IDC_SCRIPT_BTN_BASE+i)*/
/*       data — (unused)                                               */
/*  Out: LRESULT — 0 for suppressed messages; DefSubclassProc otherwise*/
/* ================================================================== */
LRESULT CALLBACK BtnSubclassProc(HWND hwnd, UINT msg, WPARAM wp,
                                   LPARAM lp, UINT_PTR uid, DWORD_PTR data)
{
    (void)data;
    switch (msg)
    {
    case WM_MOUSEMOVE:
    {
        if (g.hot_btn != (int)uid && g.hot_btn >= IDC_SCRIPT_BTN_BASE) {
            /* repaint the button that is losing hot state */
            HWND hp = GetDlgItem(GetParent(hwnd), g.hot_btn);
            if (hp) InvalidateRect(hp, NULL, FALSE);
        }
        g.hot_btn = (int)uid;
        TRACKMOUSEEVENT tme = { .cbSize=sizeof(tme), .dwFlags=TME_LEAVE,
                                .hwndTrack=hwnd };
        TrackMouseEvent(&tme); /* subscribe so WM_MOUSELEAVE clears the hot state */
        InvalidateRect(hwnd, NULL, FALSE);

        RECT rc; GetClientRect(hwnd, &rc);
        int mx = GET_X_LPARAM(lp);
        bool over_info = (mx >= rc.right - INFO_BTN_W); /* true when cursor is in the "i" zone */

        if (over_info && g.tip_btn != (int)uid) {
            g.tip_btn = (int)uid;
            int fi = g.active_tab;
            int si = (int)uid - IDC_SCRIPT_BTN_BASE;
            if (fi >= 0 && fi < g.folder_count &&
                si >= 0 && si < g.folders[fi].count)
                Meta_Parse(&g.folders[fi].scripts[si]);

            /* Compute tooltip height based on description length */
            Script *s = NULL;
            if (fi >= 0 && fi < g.folder_count &&
                si >= 0 && si < g.folders[fi].count)
                s = &g.folders[fi].scripts[si];

            int th = Tip_ComputeHeight(s);
            g.tip_h = th;

            /* Get work area of the monitor the window is on
               (accounts for taskbar, multi-monitor, maximized state) */
            MONITORINFO mi; mi.cbSize = sizeof(mi);
            HMONITOR hmon = MonitorFromWindow(g.hwnd, MONITOR_DEFAULTTONEAREST);
            GetMonitorInfo(hmon, &mi);
            RECT wa = mi.rcWork;

            /* Position tooltip to right of button; flip to left side if it would go off screen */
            POINT pt = { rc.right, 0 };
            ClientToScreen(hwnd, &pt);
            int tx = (pt.x + TIP_W > wa.right)
                     ? pt.x - rc.right - TIP_W /* flip: place left of the button */
                     : pt.x;
            int ty = pt.y;

            /* Clamp within work area on all four sides; 4 px gap from edge */
            if (ty + th > wa.bottom) ty = wa.bottom - th - 4;
            if (ty < wa.top)         ty = wa.top + 4;
            if (tx < wa.left)        tx = wa.left + 4;
            if (tx + TIP_W > wa.right) tx = wa.right - TIP_W - 4;

            SetWindowPos(g.hwnd_tip, HWND_TOPMOST, tx, ty, TIP_W, th,
                         SWP_NOACTIVATE | SWP_SHOWWINDOW);
            InvalidateRect(g.hwnd_tip, NULL, TRUE);

        } else if (!over_info && g.tip_btn == (int)uid) {
            g.tip_btn = -1;
            ShowWindow(g.hwnd_tip, SW_HIDE);
        }
        break;
    }

    case WM_MOUSELEAVE:
        if (g.hot_btn == (int)uid) { g.hot_btn = -1; InvalidateRect(hwnd, NULL, FALSE); }
        if (g.tip_btn == (int)uid) { g.tip_btn = -1; ShowWindow(g.hwnd_tip, SW_HIDE); }
        break;

    case WM_LBUTTONDBLCLK:
    {
        RECT rc; GetClientRect(hwnd, &rc);
        /* Ignore double-clicks on the info zone */
        if (GET_X_LPARAM(lp) >= rc.right - INFO_BTN_W) return 0;
        if (!g.cfg.repeat_on_dblclick) return 0;
        /* Console mode doesn't notify us when the script finishes */
        if (g.cfg.show_console) {
            PostStatus(L"Repeat mode not available in console mode.");
            return 0;
        }
        int fi = g.active_tab;
        int si = (int)uid - IDC_SCRIPT_BTN_BASE;
        if (fi < 0 || fi >= g.folder_count ||
            si < 0 || si >= g.folders[fi].count) return 0;
        if (g.repeat_mode && g.repeat_fi == fi && g.repeat_si == si) { /* double-click same script while repeating — toggle off */
            Repeat_Stop();
            g.suppress_lbuttonup = false;
            PostStatus(L"Repeat cancelled.");
            return 0;
        }
        /* Activate (also cancels any previous repeat on a different script) */
        Repeat_Stop();
        Repeat_Start(fi, si);
        g.suppress_lbuttonup = true; /* prevent the trailing WM_LBUTTONUP from triggering a run */
        PostStatus(L"Repeat: %s  •  Esc or click to stop",
                   g.folders[fi].scripts[si].name);
        InvalidateRect(hwnd, NULL, FALSE);
        if (g.hwnd_qbar) InvalidateRect(g.hwnd_qbar, NULL, FALSE);
        return 0;
    }

    case WM_LBUTTONUP:
    {
        RECT rc; GetClientRect(hwnd, &rc);
        if (GET_X_LPARAM(lp) >= rc.right - INFO_BTN_W) return 0;
        /* Suppress the trailing LBUTTONUP generated after a double-click */
        if (g.suppress_lbuttonup) {
            g.suppress_lbuttonup = false;
            return 0;
        }
        break;
    }

    case WM_ERASEBKGND:
        return 1; /* suppress default erase — Paint_ScriptButton fills the entire button surface,
                     so letting Windows erase first causes a white flash when scrolling */

    case WM_NCDESTROY:
        RemoveWindowSubclass(hwnd, BtnSubclassProc, uid);
        break;

    case WM_RBUTTONUP:
    {
        int fi = g.active_tab;
        int si = (int)GetWindowLongPtr(hwnd, GWLP_USERDATA); /* script index stored at button creation */
        if (fi < 0 || fi >= g.folder_count) break;
        if (si < 0 || si >= g.folders[fi].count) break;
        Script *s = &g.folders[fi].scripts[si];

        HMENU hm = CreatePopupMenu();
        AppendMenu(hm, MF_STRING, IDM_SCRIPT_DETAILS,
                   L"Script Details...");
        AppendMenu(hm, MF_STRING, IDM_SCRIPT_RUN_ARGS,
                   L"Run with Arguments...");
        AppendMenu(hm, MF_SEPARATOR, 0, NULL);

        AppendMenu(hm, MF_STRING, IDM_SCRIPT_FAVOURITE,
                   s->is_favourite ? L"Remove from Favourites" : L"\u2605 Add to Favourites");
        AppendMenu(hm, MF_SEPARATOR, 0, NULL);
        AppendMenu(hm, MF_STRING, IDM_SCRIPT_NOTE,
                   s->note[0] ? L"Edit Note..." : L"Add Note...");
        AppendMenu(hm, MF_SEPARATOR, 0, NULL);
        AppendMenu(hm, MF_STRING, IDM_SCRIPT_HIDE, L"Hide Script");

        POINT pt; GetCursorPos(&pt);
        int cmd = TrackPopupMenu(hm, TPM_RETURNCMD | TPM_RIGHTBUTTON,
                                  pt.x, pt.y, 0, g.hwnd, NULL);
        DestroyMenu(hm);

        switch (cmd) {
        case IDM_SCRIPT_DETAILS:
            if (DialogBoxParam(GetModuleHandle(NULL),
                    MAKEINTRESOURCE(IDD_SCRIPT_DETAILS),
                    g.hwnd, ScriptDetailsDlgProc, (LPARAM)s) == IDOK) {
                Tabs_BuildFavourites();
                Tabs_Build();
                Tabs_RebuildButtons();
            }
            break;
        case IDM_SCRIPT_RUN_ARGS:
        {
            if (DialogBoxParam(GetModuleHandle(NULL),
                    MAKEINTRESOURCE(IDD_RUN_ARGS),
                    g.hwnd, RunWithArgsDlgProc, (LPARAM)s) == IDOK) {
                /* Get args from a static buffer set by the dialog */
                Runner_Run(fi, si);
            }
            break;
        }
        case IDM_SCRIPT_FAVOURITE:
        {
            bool new_fav = !s->is_favourite;
            bool was_on_favourites = (wcscmp(g.folders[fi].name, L"Favourites") == 0); /* remember so we can return to Favourites after rebuild */
            Prefs_SetFavourite(s->gh_path, new_fav);
            /* Update the script in its real folder (not the Favourites copy) */
            for (int f2 = 0; f2 < g.folder_count; f2++) {
                if (wcscmp(g.folders[f2].name, L"Favourites") == 0) continue;
                for (int s2 = 0; s2 < g.folders[f2].count; s2++) {
                    if (wcscmp(g.folders[f2].scripts[s2].gh_path, s->gh_path) == 0) {
                        g.folders[f2].scripts[s2].is_favourite = new_fav;
                    }
                }
            }
            s->is_favourite = new_fav;
            Tabs_BuildFavourites();
            Tabs_Build();
            /* If we were on the Favourites tab and it still exists, stay on it */
            if (was_on_favourites && g.folder_count > 0 &&
                wcscmp(g.folders[0].name, L"Favourites") == 0)
                Tabs_Switch(0);
            else
                Tabs_RebuildButtons();
            break;
        }
        case IDM_SCRIPT_NOTE:
            DialogBoxParam(GetModuleHandle(NULL),
                MAKEINTRESOURCE(IDD_SCRIPT_NOTE),
                g.hwnd, ScriptNoteDlgProc, (LPARAM)s);
            break;
        case IDM_SCRIPT_HIDE:
            s->is_hidden = true;
            Prefs_SetHidden(s->gh_path, true);
            Tabs_RebuildButtons();
            break;

        }
        return 0;
    }

    } /* end switch */
    return DefSubclassProc(hwnd, msg, wp, lp);
}

/* ================================================================== */
/*  Paint_Tab                                                           */
/*  Purpose: Owner-draw handler for individual native TABCTRL items    */
/*           (legacy path, unused while CMW32TabBar is active).        */
/*           Draws the tab background, an accent top-line for the      */
/*           selected tab, and the label text.                          */
/*  In:  dis — DRAWITEMSTRUCT from WM_DRAWITEM (contains DC, item ID,  */
/*             and selection state)                                     */
/*  Out: (void)                                                         */
/* ================================================================== */
void Paint_Tab(DRAWITEMSTRUCT *dis)
{
    HDC  hdc = dis->hDC;
    RECT rc  = dis->rcItem;
    bool sel = (dis->itemState & ODS_SELECTED) != 0;

    if (sel) rc.bottom += 2; /* expand 2 px downward so selected tab overlaps and hides the tab-bar border line */

    /* Background */
    COLORREF bg = sel ? COL_BTN_NORM() : COL_TOOLBAR();
    HBRUSH br = CreateSolidBrush(bg);
    FillRect(hdc, &rc, br);
    DeleteObject(br);

    /* Border: draw on left, top, right - NOT bottom for selected tab */
    COLORREF bdr = sel ? COL_ACCENT : COL_DIVIDER();
    HPEN pen = CreatePen(PS_SOLID, 1, bdr);
    HPEN op  = SelectObject(hdc, pen);

    if (sel) {
        /* Top accent line (2px) */
        HPEN ap = CreatePen(PS_SOLID, 2, COL_ACCENT);
        SelectObject(hdc, ap);
        MoveToEx(hdc, rc.left,      rc.top, NULL);
        LineTo  (hdc, rc.right,     rc.top);
        SelectObject(hdc, op);
        DeleteObject(ap);

        /* Left and right edges */
        SelectObject(hdc, pen);
        MoveToEx(hdc, rc.left,  rc.top,    NULL); LineTo(hdc, rc.left,  rc.bottom);
        MoveToEx(hdc, rc.right - 1, rc.top, NULL); LineTo(hdc, rc.right - 1, rc.bottom);
    } else {
        /* Unselected: full border + bottom line */
        RECT border = rc;
        HBRUSH tb = CreateSolidBrush(bdr);
        FrameRect(hdc, &border, tb);
        DeleteObject(tb);
    }

    SelectObject(hdc, op);
    DeleteObject(pen);

    /* Text */
    WCHAR text[MAX_NAME] = {0};
    TCITEM ti = { .mask = TCIF_TEXT, .pszText = text,
                  .cchTextMax = MAX_NAME - 1 };
    TabCtrl_GetItem(g.hwnd_tab, dis->itemID, &ti);

    SetBkMode(hdc, TRANSPARENT);
    SetTextColor(hdc, sel ? COL_ACCENT : COL_TEXT());
    HFONT of = SelectObject(hdc, sel ? g.font_bold : g.font_ui);
    RECT tr = rc;
    if (sel) tr.bottom -= 2; /* compensate for +2 expansion so text stays centred in the original rect */
    DrawText(hdc, text, -1, &tr,
             DT_CENTER | DT_VCENTER | DT_SINGLELINE | DT_END_ELLIPSIS);
    SelectObject(hdc, of);
}
